# Generated by Django 2.1.1 on 2019-08-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('mover_position', models.CharField(blank=True, max_length=10)),
                ('target_position', models.CharField(blank=True, max_length=10)),
                ('obstacle_positions', models.CharField(blank=True, max_length=200, null=True)),
                ('question_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('referral', models.CharField(max_length=70)),
                ('schooling_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('current_theme', models.CharField(choices=[('sp', 'Space'), ('fo', 'Forest'), ('ex', 'Explorer')], max_length=20)),
                ('theme_set', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codinggamev1.Parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.CharField(blank=True, max_length=100)),
                ('num_of_tries', models.IntegerField(default=0)),
                ('code_tried', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codinggamev1.CodingQ')),
                ('student_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codinggamev1.Student')),
            ],
        ),
    ]
