# Generated by Django 2.1.1 on 2019-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_theme',
            field=models.CharField(blank=True, choices=[('sp', 'Space'), ('fo', 'Forest'), ('ex', 'Explorer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='theme_set',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
