# Generated by Django 2.1.1 on 2019-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0002_auto_20190801_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(default='cc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(default='ss', max_length=150),
            preserve_default=False,
        ),
    ]
