# Generated by Django 2.1.1 on 2019-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0003_auto_20190801_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingq',
            name='grid_size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
