# Generated by Django 2.1.1 on 2019-08-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0004_codingq_grid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='F', max_length=30),
            preserve_default=False,
        ),
    ]
