# Generated by Django 2.1.1 on 2019-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0005_auto_20190803_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_theme',
            field=models.CharField(blank=True, choices=[('sp', 'Space'), ('fo', 'Forest'), ('ex', 'Explorer'), ('ho', 'Hospital'), ('su', 'Superhero'), ('ra', 'Rabbit')], max_length=20, null=True),
        ),
    ]
