# Generated by Django 2.1.1 on 2019-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0007_codingq_secondary_target_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
