# Generated by Django 2.1.1 on 2019-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codinggamev1', '0009_student_user_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_sessions',
            field=models.TextField(default='[]'),
        ),
    ]
